testing-host-1:
  hostname: ec2-54-92-26-204.ap-northeast-1.compute.amazonaws.com
  user: ubuntu
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/opnid_skrum.pem
  forwardAgent: true
  multiplexing: false
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: testing
  roles:
    - app
    - db
  deploy_path: /usr/share/nginx/html

production-host-1:
  hostname: ec2-54-199-14-145.ap-northeast-1.compute.amazonaws.com
  user: ubuntu
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/opnid_skrum.pem
  forwardAgent: true
  multiplexing: false
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  roles:
    - app
    - db
  deploy_path: /usr/share/nginx/html
  branch: master
